### ISSUE TITLE
New ShipStation API Endpoint and Documations

### ISSUE THREAD

**Issue by paul1868** [ortega-io/ShipStation#1]
FYI - ShipStation is moving its documentation to www.shipstation.com/developer-api/  and you can use the End Point https://ssapi.shipstation.com/ without the Mashape keys.

**Comment by ghost** [comment]
Just sent a Pull request upgrading to new version API. Should be up in a few days.

**Comment by ortega-io** [comment]
I pulled and merged.

**Comment by ghost** [comment]
Thanks Otto :)
